
Student mark analysis
-------------------------
1.Average by subject and student
-
2.Highest & lowest per subject
-
3.overall class topper
-
4.pass count per subject
-
5.which subject is difficult?
-
6.Ranking students
-

In [3]:
import numpy as np

np.random.seed(25)
marks=np.random.randint(10,101,size=(20,5))
print(marks)


[[ 14  72 100  25  71]
 [ 33  54  60  18  38]
 [ 14  99  41  79  11]
 [ 49  13  98  65  13]
 [ 94  55  13  11  32]
 [ 41  58  57  83  26]
 [ 60  95  46  19  42]
 [ 20  70  57  11  96]
 [ 59  28  46  40  48]
 [ 12  15  67  83  32]
 [ 21  12  53 100  71]
 [ 94  93  84  27  24]
 [ 93  47  97  60  61]
 [ 24  81  72 100  25]
 [ 24  86  49  98  56]
 [ 63  39  23  56  63]
 [ 72  77  12  54  54]
 [ 73  55  34  19  77]
 [ 69  89  42  15  66]
 [ 46  93  29  21  47]]


In [9]:
#1.average by subjects and students

average_by_subjects=np.mean(marks,axis=0)
average_by_students=np.mean(marks,axis=1)

print("average by subjects:",average_by_subjects)
print("average by students:",average_by_students)

average by subjects: [48.75 61.55 54.   49.2  47.65]
average by students: [56.4 40.6 48.8 47.6 41.  53.  52.4 50.8 44.2 41.8 51.4 64.4 71.6 60.4
 62.6 48.8 53.8 51.6 56.2 47.2]


In [10]:
#2.highest and lowest per subject

highest=np.max(marks,axis=0)
lowest=np.min(marks,axis=0)

print("highest marks of the subject:",highest)
print("lowest marks of the subject:",lowest)


highest marks of the subject [ 94  99 100 100  96]
lowest marks of the subject [12 12 12 11 11]


In [14]:
#3.overall class topper

total_marks=np.sum(marks,axis=1)
topper=np.argmax(total_marks)

print("overall class topper is index",topper,"with marks of",total_marks[topper])

overall class topper is index 12 with marks of 358


In [16]:
#4.pass count per subject

pass_fail=marks>=40
pass_count=np.sum(pass_fail,axis=0)
print("pass count by subject:",pass_count)


pass count by subject: [12 15 15 11 12]


In [19]:
#5.which subject is difficult

difficult_subject=np.argmin(average_by_subjects)
print("difficult subject is:",difficult_subject,"with average marks of",average_by_subjects[difficult_subject])

difficult subject is: 4 with average marks of 47.65


In [22]:
#6.ranking students

ranks=np.argsort(-total_marks)
print("first rank of the class",ranks[0])
print("first 5 rank of the class",ranks[:5])

first rank of the class 12
first 5 rank of the class [12 11 14 13  0]
